export const FAKE_POPULARS = [
	{
		backdrop_path: "/uDgy6hyPd82kOHh6I95FLtLnj6p.jpg",
		first_air_date: "2023-01-15",
		genre_ids: [18, 10759],
		id: 100088,
		name: "The Last of Us",
		origin_country: ["US"],
		original_language: "en",
		original_name: "The Last of Us",
		overview:
			"Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.",
		popularity: 4873.754,
		poster_path: "/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg",
		vote_average: 8.8,
		vote_count: 2221,
	},
];

export const FAKE_RECOMMENDATIONS = [
		{
			adult: false,
			backdrop_path: "/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg",
			id: 119051,
			name: "Wednesday",
			original_language: "en",
			original_name: "Wednesday",
			overview:
				"Wednesday Addams is sent to Nevermore Academy, a bizarre boarding school where she attempts to master her psychic powers, stop a monstrous killing spree of the town citizens, and solve the supernatural mystery that affected her family 25 years ago — all while navigating her new relationships.",
			poster_path: "/9PFonBhy4cQy7Jz20NpMygczOkv.jpg",
			media_type: "tv",
			genre_ids: [10765, 9648, 35],
			popularity: 1108.767,
			first_air_date: "2022-11-23",
			vote_average: 8.637,
			vote_count: 6583,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/6Lw54zxm6BAEKJeGlabyzzR5Juu.jpg",
			id: 82856,
			name: "The Mandalorian",
			original_language: "en",
			original_name: "The Mandalorian",
			overview:
				"After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.",
			poster_path: "/eU1i6eHXlzMOlEq0ku1Rzq7Y4wA.jpg",
			media_type: "tv",
			genre_ids: [10765, 10759, 18],
			popularity: 1395.964,
			first_air_date: "2019-11-12",
			vote_average: 8.5,
			vote_count: 8459,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/2OMB0ynKlyIenMJWI2Dy9IWT4c.jpg",
			id: 1399,
			name: "Game of Thrones",
			original_language: "en",
			original_name: "Game of Thrones",
			overview:
				"Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
			poster_path: "/7WUHnWGx5OO145IRxPDUkQSh4C7.jpg",
			media_type: "tv",
			genre_ids: [10765, 18, 10759],
			popularity: 566.804,
			first_air_date: "2011-04-17",
			vote_average: 8.435,
			vote_count: 20694,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/mNHRGO1gFpR2CYZdANe72kcKq7G.jpg",
			id: 153312,
			name: "Tulsa King",
			original_language: "en",
			original_name: "Tulsa King",
			overview:
				"Just after he is released from prison after 25 years, New York mafia capo Dwight “The General” Manfredi is unceremoniously exiled by his boss to set up shop in Tulsa, Okla. Realizing that his mob family may not have his best interests in mind, Dwight slowly builds a “crew” from a group of unlikely characters, to help him establish a new criminal empire in a place that to him might as well be another planet.",
			poster_path: "/fwTv3RPRAIy0maOMns5eYRRwnDk.jpg",
			media_type: "tv",
			genre_ids: [80, 18],
			popularity: 921.078,
			first_air_date: "2022-11-13",
			vote_average: 8.59,
			vote_count: 968,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
			id: 1396,
			name: "Breaking Bad",
			original_language: "en",
			original_name: "Breaking Bad",
			overview:
				"When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
			poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
			media_type: "tv",
			genre_ids: [18],
			popularity: 422.539,
			first_air_date: "2008-01-20",
			vote_average: 8.873,
			vote_count: 11227,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/56v2KjBlU4XaOv9rVYEQypROD7P.jpg",
			id: 66732,
			name: "Stranger Things",
			original_language: "en",
			original_name: "Stranger Things",
			overview:
				"When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.",
			poster_path: "/49WJfeN0moxb9IPfGn8AIqMGskD.jpg",
			media_type: "tv",
			genre_ids: [18, 10765, 9648],
			popularity: 351.177,
			first_air_date: "2016-07-15",
			vote_average: 8.637,
			vote_count: 15212,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/vmaiCsfTQ2SSfMSWsPHcFSubPpD.jpg",
			id: 78191,
			name: "You",
			original_language: "en",
			original_name: "You",
			overview:
				"A dangerously charming, intensely obsessive young man goes to extreme measures to insert himself into the lives of those he is transfixed by.",
			poster_path: "/7bEYwjUvlJW7GerM8GYmqwl4oS3.jpg",
			media_type: "tv",
			genre_ids: [9648, 80, 18],
			popularity: 341.151,
			first_air_date: "2018-09-09",
			vote_average: 8.118,
			vote_count: 2497,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/mYegNdFjJeCISA1RDDCKBhKB4Ao.jpg",
			id: 126725,
			name: "Velma",
			original_language: "en",
			original_name: "Velma",
			overview:
				"Jinkies! This raucous reimagining of the Scooby-Doo franchise unravels the mysterious origins of Mystery, Inc. – as seen through the eyes of the gang’s beloved bespectacled detective Velma.",
			poster_path: "/zxkNhuPSHeDv3yA7sFu2RuEOGgR.jpg",
			media_type: "tv",
			genre_ids: [16, 35],
			popularity: 172.324,
			first_air_date: "2023-01-12",
			vote_average: 3.37,
			vote_count: 142,
			origin_country: ["US"],
		},
		{
			adult: false,
			backdrop_path: "/bKxiLRPVWe2nZXCzt6JPr5HNWYm.jpg",
			id: 110316,
			name: "Alice in Borderland",
			original_language: "ja",
			original_name: "今際の国のアリス",
			overview:
				"With his two friends, a video-game-obsessed young man finds himself in a strange version of Tokyo where they must compete in dangerous games to win.",
			poster_path: "/20mOwAAPwZ1vLQkw0fvuQHiG7bO.jpg",
			media_type: "tv",
			genre_ids: [18, 9648, 10759, 10765],
			popularity: 208.536,
			first_air_date: "2020-12-10",
			vote_average: 8.193,
			vote_count: 1411,
			origin_country: ["JP"],
		},
		{
			adult: false,
			backdrop_path: "/rAgezBUjU6nF0LpeP8KopRL78ZC.jpg",
			id: 120998,
			name: "Poker Face",
			original_language: "en",
			original_name: "Poker Face",
			overview:
				"This mystery-of-the-week series follows Charlie Cale, who has an extraordinary ability to determine when someone is lying. She hits the road with her Plymouth Barracuda and with every stop encounters a new cast of characters and strange crimes she can’t help but solve.",
			poster_path: "/nsOtuGh2psp0aRnUBQgePlLCfM6.jpg",
			media_type: "tv",
			genre_ids: [9648, 80],
			popularity: 139.097,
			first_air_date: "2023-01-26",
			vote_average: 8,
			vote_count: 51,
			origin_country: ["US"],
		},
	];
